### ISSUE TITLE
if 'Noise' in l.name: weights_list.append( od[l.name+'/weight'] ) KeyError: 'G_synthesis/4x4/Const/Noise/weight'

### ISSUE THREAD

**Issue by emanuelgollob** [ialhashim/StyleGAN-Tensorflow2#4]
Hi Ibraheem,
I am currently searching for a way to convert a Stylegan2 TF1 model to onnx. And the easiest way seems to save the model in TF2 first. So I found your repository. Thank you so much for sharing it!!

Saving the gs_weights.pkl worked great. 
When running the "copy_weights_to_keras_model(model.model_synthesis, all_weights)" command I, unfortunately, get this KeyError and do not really know how to work around it:

2021-07-09 11:52:15.217160: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Model created.
Weights loaded to memory.
.........Total number of parameters copied: 2101760
..Traceback (most recent call last):
  File "load5.py", line 13, in <module>
    copy_weights_to_keras_model(model.model_synthesis, all_weights)
  File "C:\Users\emanu\Downloads\StyleGAN-Tensorflow2-master\StyleGAN-Tensorflow2-master\stylegan.py", line 539, in copy_weights_to_keras_model
    if 'Noise' in l.name: weights_list.append( od[l.name+'/weight'] )
KeyError: 'G_synthesis/4x4/Const/Noise/weight'

Python 3.7, TF 2.0

If you have any ideas I would be happy for any hint.
Thx

**Comment by ialhashim** [comment]
I am no longer maintaining this repo. But you can try to achieve the same conversion the way I did it by slowly building up the list of weights and then copying them. In this case the KeyError, shows that `od[l.name+'/weight']` is missing. So maybe list all the keys in `od` and see if the name has changed due to TF versioning or so.

**Comment by emanuelgollob** [comment]
Thanks for the hint!
